Paginate when retrieving check runs and check suites
octokit/octokit.rb pull request #1321
Opened 2021-01-28 10:59 UTC by a2ikm

As far as I've investigated, the following check APIs return the link headers:

- [List check runs in a check suite](https://docs.github.com/en/rest/reference/checks#list-check-runs-in-a-check-suite)
- [List check runs for a Git reference](https://docs.github.com/en/rest/reference/checks#list-check-runs-for-a-git-reference)
- [List check suites for a Git reference](https://docs.github.com/en/rest/reference/checks#list-check-suites-for-a-git-reference)

This PR allows `auto_paginate` in them.

2021-01-28 14:50 UTC, tarebyte requested changes
Thanks for the contribution!

We let the client decide whether they want to auto paginate or not in their settings https://github.com/octokit/octokit.rb#pagination. This helps with rate limiting an other factors.

Would you mind just updating the calls to use `paginate` without the block?

2021-01-29 05:58 UTC, a2ikm commented
Thanks for the comment!
Yes, that's exactly why I added the block 😄 

> Mind just adding tests 😅

Okay, I'll add tests 👍 
It may take a time because we should update VCR cassetts to include two or more documents in the lists.

2021-05-01 17:32 UTC, lastthyme approved these changes

2021-08-29 19:46 UTC, matiasalbarello approved these changes

2022-02-28 15:28 UTC, lhmzhou approved these changes

2022-03-17 07:51 UTC, kou commented
@a2ikm Do you still want to add tests for this changes?

@matiasalbarello @lhmzhou Do you want to help it?

2022-03-17 07:52 UTC, Smiley278 commented
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Sutou Kouhei ***@***.***>
Sent: Thursday, March 17, 2022 3:51:49 AM
To: octokit/octokit.rb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [octokit/octokit.rb] Paginate when retrieving check runs and check suites (#1321)


@a2ikm<https://github.com/a2ikm> Do you still want to add tests for this changes?

@matiasalbarello<https://github.com/matiasalbarello> @lhmzhou<https://github.com/lhmzhou> Do you want to help it?

—
Reply to this email directly, view it on GitHub<https://github.com/octokit/octokit.rb/pull/1321#issuecomment-1070484632>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXT5KQ7MQ35YF5HB3PPLME3VALQBLANCNFSM4WW3JCOA>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-05-18 15:34 UTC, a2ikm commented
@kou 
Sorry for my too late reaction.
I have no time to add tests.

On the other hand, @matiasalbarello's PR looks good.
So please continue with it 🙏

2022-05-25 16:44 UTC, nickfloyd commented
Closing this one in favor of: @matiasalbarello's [PR](https://github.com/octokit/octokit.rb/pull/1415).  Thank you @a2ikm for your effort here and for getting this work in motion.  ❤️

2022-05-25 16:44 UTC, closed without merging