Update README to remove Octokit client instance creation with username and password.
octokit/octokit.rb pull request #1338
Opened 2021-05-06 06:21 UTC by RaminMammadzada

As of November 2020, the GitHub API does not allow you to authenticate to the API via username and password. See https://github.blog/changelog/2020-11-13-token-authentication-required-for-api-operations/ for more details.

Therefore login with user and password must be removed from the README file of the project.

2021-05-11 20:03 UTC, tarebyte requested changes

2021-05-11 20:03 UTC, tarebyte commented on README.md
> +client = Octokit::Client.new(:access_token => '[personal_access_token]!')
```suggestion
client = Octokit::Client.new(:access_token => 'personal_access_token')
```

2021-05-11 20:03 UTC, tarebyte commented on README.md
> +# Set access_token instead of login and password if you use personal access token
```suggestion
```

2021-05-15 11:12 UTC, tarebyte approved these changes

2021-05-15 11:27 UTC, merged

2021-05-18 17:53 UTC, hmharvey commented
👋🏻 We thank you for helping us keep our library up to date! However, these comments were added as part of https://github.com/octokit/octokit.rb/issues/1313 to address the username/password deprecation and are still a valid way to authenticate! Thus, I've opened up a PR to revert them.