Document how and when the library raises exceptions
octokit/octokit.rb pull request #1412
Opened 2022-04-14 11:20 UTC by timrogers

This adds a section to the readme which explains when the library will raise exceptions and how you can work with them.

I did some work with `octokit/octokit.rb` and `octokit/octokit.js` recently, and I found that not having this meant that I had to do a bunch of digging myself to understand how I should handle unhappy paths.

As well as adding the error handling documentation, this PR also makes a few other small changes to the README: correcting, renaming and restructuring headings.

2022-04-14 13:53 UTC, nickfloyd requested changes
Hey @timrogers thanks for these additions!  I just left one small nit on the bulleted items for the errors.  Let me know what you think!

2022-04-14 13:53 UTC, nickfloyd commented on README.md
> +* a `403 Forbidden` error with a "rate limited exceeded" message will lead
Just a small nit.

```suggestion
* A `403 Forbidden` error with a "rate limited exceeded" message will lead
```

2022-04-14 16:31 UTC, nickfloyd approved these changes
👍  LGTM!

2022-04-14 16:42 UTC, hmharvey commented
> 👍 LGTM! Side note - did you intend your base branch to be octokit:4-stable - This feels like the base should be master given it's just a docs change and not a hotfix.

`octokit:4-stable` is still the correct branch! `master` has significantly diverged at this point 😄

2022-04-14 19:02 UTC, timrogers commented
I'm not allowed to merge this, which I'm guessing is due to the outstanding GitHub checks (which aren't needed due to the `ci skip`!). 

I'll just let the checks run for the last commit to get around this 🙏

2022-04-14 19:03 UTC, timrogers commented
> `octokit:4-stable` is still the correct branch! `master` has significantly diverged at this point 😄 

Interesting! 🤔 Is there some clean-up we can or should do here? Perhaps we could delete `master` and create a new `main` branch starting from `4-stable`?

2022-04-14 19:14 UTC, nickfloyd commented
> Interesting! 🤔 Is there some clean-up we can or should do here? Perhaps we could delete `master` and create a new `main` branch starting from `4-stable`?

Yeah, we've got plans to get things cinched up around builds, workflow, and CI. Great work has already been done on octokit Ruby; it will take a bit of effort, but I am definitely looking forward to tackling things like these so that we can get this to a point where it is up to date and more welcoming to contributors!

2022-04-14 20:15 UTC, timrogers commented
> > Interesting! 🤔 Is there some clean-up we can or should do here? Perhaps we could delete `master` and create a new `main` branch starting from `4-stable`?
> 
> Yeah, we've got plans to get things cinched up around builds, workflow, and CI. Great work has already been done on octokit Ruby; it will take a bit of effort, but I am definitely looking forward to tackling things like these so that we can get this to a point where it is up to date and more welcoming to contributors!

Wonderful! 🙌🏻

2022-04-14 20:17 UTC, timrogers commented
@nickfloyd This should be ready for merge now. Thank you so much!

2022-04-19 13:46 UTC, imwiss commented
Thanks for updating this, @timrogers! ✨

2022-04-19 13:46 UTC, merged