Adds ability to update pull request branch
octokit/octokit.rb pull request #1472
Opened 2022-08-22 16:14 UTC by bjedrocha

Resolves #1471 

As per https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request-branch. I couldn't get the specs to work with VCR despite creating a test repo and setting all relevant ENV vars. I decided to stub the request instead.

2022-08-22 16:52 UTC, timrogers requested changes
👋🏻 Thanks for taking the time to make this PR! I have a suggestion on how we could make the behaviour of the method a little nicer, and on how we test it.

2022-08-22 16:52 UTC, timrogers commented on lib/octokit/client/pull_requests.rb
> +        put "#{Repository.path repo}/pulls/#{number}/update-branch", options
What do you thinking of using `#boolean_from_response` here? Looking at the API, it appears that the response is not super useful - you just want to know if it worked or not.

```suggestion
        boolean_from_response(:put, "#{Repository.path repo}/pulls/#{number}/update-branch", options)
```

2022-08-22 16:52 UTC, timrogers commented on spec/octokit/client/pull_requests_spec.rb
> +  describe '.update_pull_request_branch' do
We should test the return value of `#update_pull_request_branch` in here.

2022-08-22 17:56 UTC, bjedrocha commented
Thanks for the quick review - I can address that feedback shortly. What are your thoughts on having the API called stubbed vs. having a cassette for it?

2022-08-22 18:11 UTC, timrogers commented
> Thanks for the quick review - I can address that feedback shortly. What are your thoughts on having the API called stubbed vs. having a cassette for it?

I'm okay for it to be stubbed. Could we stub it with an actual response for better test. overage?

2022-08-23 16:31 UTC, bjedrocha commented
Addressed your feedback. I've changed `update_pull_request_branch` to return a simple boolean if the request succeeds. I also improved the test coverage by adding specs for the requests that fail. I didn't stub the response body as we're not doing anything with anyway but that can always be added if you think it provides value.

2022-08-23 16:33 UTC, tride1997 commented
1472

Vào 23:32, Th 3, 23 thg 8, 2022 Bart Jedrocha ***@***.***> đã
viết:

> Addressed your feedback. I've changed update_pull_request_branch to
> return a simple boolean if the request succeeds. I also improved the test
> coverage by adding specs for the requests that fail. I didn't stub the
> response body as we're not doing anything with anyway but that can always
> be added if you think it provides value.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/octokit/octokit.rb/pull/1472#issuecomment-1224315252>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMLANDXD7NGCF5C6I6VJ62TV2T4I3ANCNFSM57IIZBNQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-08-23 16:50 UTC, timrogers approved these changes

2022-08-23 16:55 UTC, merged