Add new methods to get org team permissions for repo
octokit/octokit.rb pull request #1474
Opened 2022-08-23 20:00 UTC by juanmrad

This PR adds the new methods for [Check team permissions for a repository](https://docs.github.com/en/rest/teams/teams#check-team-permissions-for-a-repository)

cc/ @audreee

2022-08-24 11:04 UTC, timrogers approved these changes

2022-08-24 11:05 UTC, timrogers commented on spec/octokit/client/organizations_spec.rb
> +    describe '.team_permission_level', :vcr do
It looks like this test is failing at the moment because the VCR cassette is missing. It's fine just to use stubbing instead.

2022-08-25 11:01 UTC, timrogers requested changes

2022-08-25 11:01 UTC, timrogers commented on lib/octokit/client/organizations.rb
> +      def team_permission_level(org, team_slug, owner, repo, options = {})
I'm not convinced by this name, but I'm not sure what the best option would be. What do you think? Some ideas that come to mind:

* `#team_permissions_for_repo`
* `#check_team_permissions_for_repo`
* `#team_permissions_level_for_repo`
* `#check_team_permissions_for_repo`

2022-08-25 18:03 UTC, timrogers commented on lib/octokit/client/organizations.rb
> +        get "#{Organization.path(org)}/teams/#{team_slug}/repos/#{owner}/#{repo}", options
It feels a bit weird that this method returns an empty string if the team _does_ have permissions on the repo. 

I wonder if we should use `#boolean_from_response` here to return a boolean instead, which feels like a nicer API for this Ruby method.

Another option that comes to mind is to have two versions of the method - one which sends the `Accept: application/vnd.github.v3.repository+json` header and gets a JSON response, and one which returns a boolean.

2022-08-29 12:31 UTC, timrogers requested changes

2022-08-29 23:02 UTC, juanmrad commented on lib/octokit/client/organizations.rb
> +        if options.key?(:accept)
So it is actually:
- By default empty string if permissions exist.
- If no permissions exist then a 404 will be thrown.
- When given the Header you get a JSON response.

2022-08-30 10:34 UTC, timrogers requested changes
Nearly there - just some small cosmetic changes left which I will take care of ❤️

2022-08-30 10:34 UTC, timrogers commented on lib/octokit/client/organizations.rb
> +      def team_permissions_for_repo(org, team_slug, owner, repo, options = {})
```suggestion
      def team_permissions_for_repo(org, team_slug_or_id, owner, repo, options = {})
```

2022-08-30 10:34 UTC, timrogers commented on lib/octokit/client/organizations.rb
> +      # @param team_slug [String, Integer] Team slug or Team ID.
```suggestion
      # @param team_slug_or_id [String, Integer] Team slug or Team ID.
```

2022-08-30 10:34 UTC, timrogers commented on lib/octokit/client/organizations.rb
> +        get "#{Organization.path(org)}/teams/#{team_slug}/repos/#{owner}/#{repo}", options
```suggestion
        get "#{Organization.path(org)}/teams/#{team_slug_or_id}/repos/#{owner}/#{repo}", options
```

2022-08-30 10:34 UTC, timrogers commented on spec/octokit/client/organizations_spec.rb
> +      it 'returns true when a team has permissions for a repo' do
```suggestion
      it 'returns an empty string when a team has permissions for a repo' do
```

2022-08-30 10:34 UTC, timrogers commented on spec/octokit/client/organizations_spec.rb
> +      it 'returns false when a team does not have permissions for a repo' do
```suggestion
      it 'raises an error when a team does not have permissions for a repo' do
```

2022-08-30 11:36 UTC, timrogers approved these changes

2022-08-30 11:36 UTC, merged