Add GHES Manage API client
octokit/octokit.rb pull request #1688
Opened 2024-05-16 13:52 UTC by manue1

Resolves #ISSUE_NUMBER

----

### Before the change?

* 

### After the change?

* 

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [ ] No

----

2024-06-04 20:57 UTC, nickfloyd requested changes
Hey @manue1 thanks for the changes here and apologies for the delay on getting a review out to you. ❤️  These changes look good overall, there is one change to the console message produced from the Faraday check - have a look at what I am proposing and let me know what you think.

2024-06-04 20:57 UTC, nickfloyd commented on lib/octokit/default.rb
> +    Octokit::Warnable.octokit_warn 'To use retry middleware with Faraday v2.0+, install `faraday-multipart` gem'
```suggestion
    Octokit::Warnable.octokit_warn 'To use multipart middleware with Faraday v2.0+, install `faraday-multipart` gem; note: this is used by the ManageGHES client for uploading licenses'
```

2024-06-05 08:38 UTC, alejndr0 commented
> Hey @manue1 thanks for the changes here and apologies for the delay on getting a review out to you. ❤️ These changes look good overall, there is one change to the console message produced from the Faraday check - have a look at what I am proposing and let me know what you think.

Hey nick! Please do not merge this PR yet, just been notified I need to make a quick modification, but I will not be able to do it until Friday :)

2024-06-10 13:30 UTC, nickfloyd commented
@alejndr0 Thx for the updates... I am looking at this now and will get it reviewed and hopefully released this morning.

2024-06-10 17:24 UTC, nickfloyd approved these changes

2024-06-10 17:24 UTC, merged